### ISSUE TITLE
feat(bin): Up Subcommand

### ISSUE THREAD

**Issue by refcell** [anton-rs/op-up#18]
### Description

As part of #17, this task is to move the `Stack` logic in [`stack.rs`](https://github.com/anton-rs/op-up/blob/main/bin/opup/src/stack.rs) to an `up` subcommand. Most of the time, `op-up` will be run without specifying this subcommand since it is redundant to execute `op-up up`.

The `up` subcommand itself should have a `--devnet` flag that can be used to override the local `stack.toml` and default config for a hard-coded devnet stack configuration.

Since this subcommand will have flags and some additional logic, it should be moved to a new `up.rs` file. So, just moving the contents of [`stack.rs`](https://github.com/anton-rs/op-up/blob/main/bin/opup/src/stack.rs) to this new file and then dispatching the top-level `cli.rs` to this handler by default and when the `up` subcommand is provided.

**Comment by merklefruit** [comment]
Closed in #38
