### ISSUE TITLE
bug: cargo run

### ISSUE THREAD

**Issue by solidoracle** [anton-rs/op-up#69]
cloned the op-up repo and when I run cargo run I get the error:
`failed to run custom build command for jemalloc-sys v0.5.4+5.3.0-patched`

**Comment by merklefruit** [comment]
Hi @solidoracle what OS are you on? Windows with WSL?

**Comment by solidoracle** [comment]
@merklefruit MAC M1

**Comment by merklefruit** [comment]
1. make sure you have jemalloc: `brew install jemalloc`
2. if that isn't enough, try running without the jemalloc feature: `cargo run --no-default-features`

**Comment by solidoracle** [comment]
found issue: was running the project located in a directory with spaces in the path
