### ISSUE TITLE
chore(deps): check for missing dependencies

### ISSUE THREAD

**Issue by merklefruit** [anton-rs/op-up#71]
In the stages that don't use Docker (e.g. L1 genesis, L2 genesis, Prestate, Allocs) we should double check which dependencies are used. In particular, the `make` commands could hide dependencies by launching scripts with multiple steps inside.

---

- Here we should add `make` to the list of binaries

https://github.com/anton-rs/op-up/blob/ce29d5a847985c165bbb75f45bf5e42b8cb524ad/bin/opup/src/deps.rs#L25-L26

- for `go`, we need to make a separate function `go()` similar to `foundry()` in the same file. The function should perform the `brew install go` command on MacOS, and use the `package_manager()` helper to install the package called `golang-go` on Linux. We can skip Windows at the moment.

**Comment by solidoracle** [comment]
@merklefruit I'd like to tackle this
